version: "3.7"

services:
    mongodb:
        image: mongo:5.0.6
        restart: always
        volumes:
            - mongo-data:/data
    wtb:
        image: wtb:latest
        restart: always
        environment:
            - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
        depends_on:
            - mongodb
        links:
            - mongodb
volumes:
    mongo-data:
