services:
  mongodb:
   image: mongo:6.0.5
   restart: unless-stopped
   volumes:
   - type: bind
     source: ./mongo-data
     target: /data/db
  wtb:
   image: wtb:latest
   restart: unless-stopped
   environment:
   - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
   depends_on:
   - mongodb
   links:
   - mongodb
volumes:
  mongo-data:
