services:
  mongodb:
   image: mongo:6.0.3
   restart: unless-stopped
   volumes:
   - mongo-data:/data
  wtb:
   image: wtb:latest
   restart: unless-stopped
   environment:
   - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
   depends_on:
   - mongodb
   links:
   - mongodb
volumes:
  mongo-data:
